---
user_name: "{{ ansible_user_id }}"
user_home: "{{ ansible_env.HOME }}"
user_email: "fedorov7@gmail.com"
git_user_name: "Alexander Fedorov"

astronvim_repo: "git@github.com:fedorov7/astronvim-config-v4.git"

nvm_version: "v0.39.7"
node_version: "--lts"
