---
- name: Install rustup and llvm
  become: true
  community.general.pacman:
    name:
      - rustup
      - llvm
    state: present

- name: Check current default Rust toolchain
  command: rustup default
  register: rustup_current
  changed_when: false
  failed_when: false

- name: Set Rust stable as default toolchain
  command: rustup default stable
  when: "'stable' not in (rustup_current.stdout | default(''))"
