---
- name: Install C/C++ toolchain
  become: true
  community.general.pacman:
    name:
      - cmake
      - ninja
      - meson
      - gcc
      - clang
      - clang-tools-extra
      - ccache
      - mold
      - lldb
      - cppcheck
      - bear
      - bpftrace
      - gcovr
      - lcov
    state: present
