---
- name: Install Python tooling
  become: true
  community.general.pacman:
    name:
      - uv
      - ruff
      - python-pip
      - python-pytest
      - mypy
      - pyright
      - python-black
      - python-pipx
    state: present

- name: Install Python 3.12 via uv
  command: uv python install 3.12
  register: uv_python
  changed_when: "'Installed' in uv_python.stdout"
